library group_call;

import 'dart:async';
import 'dart:developer';
import 'dart:io';
import 'dart:math' as math;

import 'package:collection/collection.dart';
import 'package:flutter/material.dart';
import 'package:flutter_background/flutter_background.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_slidable/flutter_slidable.dart';
import 'package:flutter_webrtc/flutter_webrtc.dart';
import 'package:intl/intl.dart';
import 'package:livekit_client/livekit_client.dart';
import 'package:videocall/common/widgets/stateless/buttons/custom_elevated_button.dart';
import 'package:videocall/common/widgets/stateless/buttons/float_action_button_video.dart';
import 'package:videocall/common/widgets/stateless/call/video_render/participant.dart';
import 'package:videocall/common/widgets/stateless/call/video_render/participant_info.dart';
import 'package:videocall/common/widgets/stateless/custom_avatar_image.dart';
import 'package:videocall/common/widgets/stateless/skeleton/list_skeleton.dart';
import 'package:videocall/core/di/injector.dart';
import 'package:videocall/core/routes/app_navigation.dart';
import 'package:videocall/core/utils/live_kit_until.dart';
import 'package:videocall/core/utils/screen_utils.dart';
import 'package:videocall/core/utils/snack_bar.dart';
import 'package:videocall/domain/entities/message_call_entity.dart';
import 'package:videocall/presentation/call/group_call/bloc/group_call_pin_message_bloc.dart';
import 'package:videocall/presentation/call/group_call/cubit_call_group_status/call_group_status_cubit.dart';

part 'pages/group_call_main_page.dart';
part 'pages/group_call_waiting_page.dart';
part 'pages/group_calling.dart';
part 'pages/group_calling_page.dart';
part 'views/list_message_view.dart';
part 'widgets/controls.dart';
part 'widgets/group_call_message_item.dart';
part 'widgets/group_message_button.dart';
part 'widgets/icon_wrapper.dart';
